### ISSUE TITLE
ChannelStore_SignupFlow Not Working proper

### ISSUE THREAD

**Issue by chaklasiyanikunj** [rokudev/samples#14]
Rokupay Example ChannelStore_SignupFlow Not Working proper. Enter the email Address dialog will open and press back key or back button and again open same dialog box then not working keyboard properly.

**Comment by jduval23** [comment]
Hi,

I can reproduce the issue you are seeing. Specific steps to repro are as follows:

1. Click **Aleady a Subscriber (log in)**.
2. Press Back button on Roku remote control or click **Back** in keyboard dialog.
3. Observe that you can no longer navigate to characters on the keyboard.

We will further investigate in order to determine a solution. 

Thanks,

Roku Developer Relations

**Comment by jduval23** [comment]
Hi, 

This sample has been fixed.

Thanks,

Roku Developer Relations

**Comment by chaklasiyanikunj** [comment]
Thank you for your response. Finally, It's Working Fine. I think as a viewer perspective Email Password as EditTextBox and one Button Submit. Maintain Focus Between all three children node and submit button check username and password right or not. click to display a another view. Is It Possible in Roku?
